spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hejuen321.
    url: jdbc:mysql://123.56.164.235:3306/public_welfare?useUnicode=true&useSSL=false&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

ip: 123.56.164.235 # 根据自己FastDFS服务器修改

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 123.56.164.235:22122
  web-server-url: http://123.56.164.235/
