server:
  port: 12331

ip: 123.56.164.235 # 根据自己FastDFS服务器修改

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 123.56.164.235:22122
  web-server-url: http://123.56.164.235/